# Import Library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import numpy as np

# Load Dataset

In [2]:
data = pd.read_csv('Jumlah_desa_jatim.csv')
data.head()

,id,id_index,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,periode_update,kategori,jumlah,satuan,tahun
0,168,1336,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,BERKEMBANG,31,DESA,2025
1,168,1337,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,MAJU,149,DESA,2025
2,168,1338,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,MANDIRI,101,DESA,2025
3,168,1339,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,SANGAT TERTINGGAL,0,DESA,2025
4,168,1340,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,TERTINGGAL,0,DESA,2025

# check missing value

In [3]:
data.isnull().sum()

id                     0
id_index               0
kode_provinsi          0
nama_provinsi          0
kode_kabupaten_kota    0
nama_kabupaten_kota    0
periode_update         0
kategori               0
jumlah                 0
satuan                 0
tahun                  0
dtype: int64

# Handling Missing Value

In [4]:
data.fillna(data.mean(numeric_only=True), inplace=True)
data

,id,id_index,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,periode_update,kategori,jumlah,satuan,tahun
0,168,1336,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,BERKEMBANG,31,DESA,2025
1,168,1337,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,MAJU,149,DESA,2025
2,168,1338,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,MANDIRI,101,DESA,2025
3,168,1339,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,SANGAT TERTINGGAL,0,DESA,2025
4,168,1340,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2025,TERTINGGAL,0,DESA,2025
...,...,...,...,...,...,...,...,...,...,...,...
185,261,1521,35,JAWA TIMUR,3579,KOTA BATU,2025,BERKEMBANG,0,DESA,2025
186,261,1522,35,JAWA TIMUR,3579,KOTA BATU,2025,MAJU,0,DESA,2025
187,261,1523,35,JAWA TIMUR,3579,KOTA BATU,2025,MANDIRI,19,DESA,2025
188,261,1524,35,JAWA TIMUR,3579,KOTA BATU,2025,SANGAT TERTINGGAL,0,DESA,2025
189,261,1525,35,JAWA TIMUR,3579,KOTA BATU,2025,TERTINGGAL,0,DESA,2025

# EDA Timeseries